### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by Urian-oy** [c-yn/IRNeXt#3]
As we kown, in the OTS dataset, a clear image corresponds to many foggy images. How to process images on the dataset folder to make the program run

**Comment by c-yn** [comment]
Hi, please refer to Line 64 of Dehazing/OTS/data/data_load.py.

**Comment by Urian-oy** [comment]
> Hi, please refer to Line 64 of Dehazing/OTS/data/data_load.py.

Thanks!I have already done.There is a para(ps=256) need to seu up . Dehazing/OTS/data/data_load.py--->line 10: DeblurDataset(image_dir, ps=128),

**Comment by Urian-oy** [comment]
> Hi, please refer to Line 64 of Dehazing/OTS/data/data_load.py.

By the way , why I set 'ps' other number, it doesnot work.There are some magic?

**Comment by c-yn** [comment]
The ps number must be divided by 4.

**Comment by Urian-oy** [comment]
> The ps number must be divided by 4.

Thanks a lot.I will try it.Have a nice day

**Comment by c-yn** [comment]
Thanks. Also may be 32. It depends on the downsampling rate of the model.
