### ISSUE TITLE
About the file "data_load.py" in  path:OTS--->data

### ISSUE THREAD

**Issue by Urian-oy** [c-yn/IRNeXt#5]
Excuse me , I still don't understand why the **‘ps’ parameter** in this file **can't be set to 256**, I tried **128 and 64 can run**, but like set to 256, it will be wrong, my ps understanding is that it is the size of an image cropped

**Comment by Urian-oy** [comment]
Here is the code pic

**Comment by c-yn** [comment]
Yes, ps is the size of the cropped image.
What errors did you encounter when setting ps=256?

**Comment by Urian-oy** [comment]
> Yes, ps is the size of the cropped image. What errors did you encounter when setting ps=256?
I think this may be due to the fact that there are images in the dataset with dimensions (height or width) less than 256.I will try out it and reply u ,ths your reply in time.
![error](https://github.com/c-yn/IRNeXt/assets/71719371/9b9b3af7-953c-40e2-85fd-4467dcd1bc54)

**Comment by c-yn** [comment]
Yes, there are some images smaller than 256*256.

You can remove them or pad them. We chose to manually remove them when preparing the dataset.

**Comment by Urian-oy** [comment]
> Yes, there are some images smaller than 256*256.
> 
> You can remove them or pad them. We chose to manually remove them when preparing the dataset.

Yes.Thanks for your work.
