### ISSUE TITLE
About image deblurring task

### ISSUE THREAD

**Issue by Lixuanhe** [c-yn/IRNeXt#6]
Following the settings outlined in your paper, I set the coefficient n of the CNNBlock to 13. However, despite adhering to these parameters, the resulting PSNR of the trained model only reached 26.5. I was wondering if you could provide further details or insights into the training process for image deblurring.

Any additional information or guidance you could offer would be greatly appreciated.

Thank you for your time and consideration.

**Comment by c-yn** [comment]
Hi, thanks for your interest.
The code has been released.

**Comment by Lixuanhe** [comment]
Thank you very much！
