### ISSUE TITLE
Questions about training on Dehazing task

### ISSUE THREAD

**Issue by Sky-Brid** [c-yn/IRNeXt#8]
​	你好，我是一名研一的硕士生。我想问一下，在训练 RESIDE-Indoor 的过程中，我将batch size 设置为 8，学习率采用余弦退火从 1e-4 衰减到 1e-6，与你发布的源码一样，有没有其他需要修改的超参？
​	我根据您发布的代码对模型进行了训练，但我使用的是 PyTorch 2.0.1（显卡为 3090）。在模型训练的前 15 个 epoch 中，PSNR 可以达到约 27 dB，但随后 PSNR 就下降到了约 18 dB，且没有再上升过。我想了解一下，在您的训练过程中，模型的性能是如何变化的？通常情况下，模型会在多少个 epoch 内收敛？
        希望您能解答一下我的问题，感谢！

**Comment by c-yn** [comment]
你好，采用公布代码中的默认参数即可得到文章中的结果。除了修改了bs，请检查数据集等是否配置正确。

**Comment by Sky-Brid** [comment]
数据集我是在官网下载的，除了数据集还有什么原因导致吗

**Comment by Sky-Brid** [comment]
我是在这个网址下载的ITS：https://sites.google.com/view/reside-dehaze-datasets/reside-standard

**Comment by c-yn** [comment]
你好，数据集配置正确，用发布的代码和默认参数应该没啥问题的。请仔细检查一下。至于到底是什么原因，我这不好说，毕竟是你那边操作的。

**Comment by Sky-Brid** [comment]
好的，能否问下在您的训练过程中，模型的性能是如何变化的？通常情况下，模型会在多少个 epoch 内收敛？

**Comment by c-yn** [comment]
性能总体是上升的。300epoch相对于其他工作，不是很多。我的配置中，大概270差不多就收敛了。

**Comment by Sky-Brid** [comment]
好的，感谢！
